### ISSUE TITLE
ThreadCell should always support Send + Sync

### ISSUE THREAD

**Issue by npwoods** [cehteh/threadcell#2]
I see that with https://github.com/cehteh/threadcell/commit/8dba13e285b14c89787245c09f9a0b813e4d0983 a change was made to only support `Send + Sync` when the underlying type supports `Send`.  While it is possible that I'm missing something, I think that this defeats the purpose of `ThreadCell`, at least my usage thereof.

It feels that one should be able to use `ThreadCell` as a receptacle for data that might otherwise not support either `Send` nor `Sync`, and be able to pass that around to different threads, but with the expectation that any usage that goes beyond passing it around would only happen on the original thread.

I see the comment for the commit suggests following the precedent of `Mutex`.  IMHO `Mutex` is a different case because mutexes are about synchronization, not about confining usage to a particular thread.

Or am I missing something?

**Comment by cehteh** [comment]
Am Tue, 04 Jun 2024 13:18:12 -0700
schrieb npwoods ***@***.***>:

> I see that with
> https://github.com/cehteh/threadcell/commit/8dba13e285b14c89787245c09f9a0b813e4d0983
> a change was made to only support `Send + Sync` when the underlying
> type supports `Send`.  While it is possible that I'm missing
> something, I think that this defeats the purpose of `ThreadCell`, at
> least my usage thereof.

You can't magically make things Send that are not (for any generic
cases). Some objects may hold (OS) resources that are thread local for
example.

It might be true that in your use case you have some object that is not
Send but can be made Send with some caution. ThreadCell is not the tool
for that case. Generally this would need some more unsafe code
(construction, acquisition). There are crates for that.

> 
> It feels that one should be able to use `ThreadCell` as a receptacle
> for data that might otherwise not support either `Send` nor `Sync`,
> and be able to pass that around to different threads, but with the
> expectation that any usage that goes beyond passing it around would
> only happen on the original thread.
> 
> I see the comment for the commit suggests following the precedent of
> `Mutex`.  IMHO `Mutex` is a different case because mutexes are about
> synchronization, not about confining usage to a particular thread.

Thats right, ThreadCell does not implement synchronization, but similar
to a MutexGuard as that confines use to a single thread. You may also
look at the AtomicRefCell crate which is closer related to ThreadCell.


> 
> Or am I missing something?
>

**Comment by npwoods** [comment]
I think the issue is that I'm trying to do something narrower than the concept expressed by Rust's `Send` trait.  I want to have something that can only be used to a specific thread, but to be able to pass it around opaque across different threads, and ultimately make use of it in a non-opaque fashion on the original thread.  Furthermore thread local variables are undesirable because they are essentially globals.

I suppose I could do something like this (pseudo code of course):
````
thread_local!(HASHMAP) = RefCell::new(HashMap<usize, T>();
thread_local!(HASHMAP_COUNTER) = AtomicUsize::new(0);

fn my_code() {
    ...
    let cant_be_used_on_other_threads = { ... };
    let opaque_ref = HASHMAP.insert(HAShMAP_COUNTER.fetch_add(1));
    
    invoke_on_another_thread(|| {
        ...pass around opaque_ref...
        invoke_on_original_thread(|| {
            ...
            let cant_be_used_on_ther_threads_ref = HASHMAP.get(opaque_ref);
            cant_be_used_on_ther_threads_ref.finally_do_something_cool();
        }
    }
}
````

The reading I'm getting is that this is not really part of the scope of `ThreadCell`.  Corrections welcome of course.

Or I could just use `threadcell` `0.6.0` :-)

**Comment by cehteh** [comment]
Am Wed, 05 Jun 2024 04:28:52 -0700
schrieb npwoods ***@***.***>:

> I think the issue is that I'm trying to do something narrower than
> the concept expressed by Rust's `Send` trait.  I want to have
> something that can only be used to a specific thread, but to be able
> to pass it around opaque across different threads, and ultimately
> make use of it in a non-opaque fashion on the original thread.
> Furthermore thread local variables are undesirable because they are
> essentially globals.
> 
> I suppose I could do something like this (pseudo code of course):
> ````
> thread_local!(HASHMAP) = RefCell::new(HashMap<usize, T>();
> thread_local!(HASHMAP_COUNTER) = AtomicUsize::new(0);
> 
> fn my_code() {
>     ...
>     let cant_be_used_on_other_threads = { ... };
>     let opaque_ref = HASHMAP.insert(HAShMAP_COUNTER.fetch_add(1));
>     
>     invoke_on_another_thread(|| {
>         ...pass around opaque_ref...
>         invoke_on_original_thread(|| {
>             ...
>             let cant_be_used_on_ther_threads_ref =
> HASHMAP.get(opaque_ref);
> cant_be_used_on_ther_threads_ref.finally_do_something_cool(); }
>     }
> }
> ````
> 
> The reading I'm getting is that this is not really part of the scope
> of `ThreadCell`.  Corrections welcome of course.
> 
> Or I could just use `threadcell` `0.6.0` :-)

That I removed the Send impl because its unsound, so better dont use
that.

Whats the bigger picture here? why does it have to be opaque. Why
does it need to be forced Send, HashMap should be Send when it stores
keys/values that are Send. RefCell is Send too (but i may suggest
AtomicRefCell when threads are involved)

Either way making something opaque and giving a thread exclusive access
are different things which likely should not be done in one thing.

Something being !Send would have some reason, even if you can force
making it Send it may break in future versions or on other platforms.

OTOH making something opaque should be doable. The receiver would need
some kind of token (could be the thread id?) to dereference it, but that
skims in the security-by-obscurity business. What do you really want to
achieve by that?

For ThreadCell i once thought about i could add a 'send(&self, tid:
ThreadId)' API. I've forgotten why i didn't do that, perhaps the
necessary stuff wasn't stable back then, maybe because its pretty ugly
to use without synchronization. I am pretty sure i never needed such
functionality at least.



>

**Comment by cehteh** [comment]
Am Wed, 05 Jun 2024 04:28:52 -0700
schrieb npwoods ***@***.***>:

> I think the issue is that I'm trying to do something narrower than
> the concept expressed by Rust's `Send` trait.  I want to have
> something that can only be used to a specific thread, but to be able
> to pass it around opaque across different threads, and ultimately
> make use of it in a non-opaque fashion on the original thread.
> Furthermore thread local variables are undesirable because they are
> essentially globals.
> 
> I suppose I could do something like this (pseudo code of course):
> ````
> thread_local!(HASHMAP) = RefCell::new(HashMap<usize, T>();
> thread_local!(HASHMAP_COUNTER) = AtomicUsize::new(0);
> 
> fn my_code() {
>     ...
>     let cant_be_used_on_other_threads = { ... };
>     let opaque_ref = HASHMAP.insert(HAShMAP_COUNTER.fetch_add(1));
>     
>     invoke_on_another_thread(|| {
>         ...pass around opaque_ref...
>         invoke_on_original_thread(|| {
>             ...
>             let cant_be_used_on_ther_threads_ref =
> HASHMAP.get(opaque_ref);
> cant_be_used_on_ther_threads_ref.finally_do_something_cool(); }
>     }
> }
> ````
> 
> The reading I'm getting is that this is not really part of the scope
> of `ThreadCell`.  Corrections welcome of course.
> 
> Or I could just use `threadcell` `0.6.0` :-)
> 

Just a brainfart:

you could make a

struct SendCell<T> {
	tc: ThreadCell<T>,
        owner: Cow<'static, str>,
}


Allowing to obtain a Guard only when the owner matches (or is empty?)

let st = SendCell::new(123);

st.send("consumer_thread");


thread_spawn(|| { let guard = st.acquire_guard("consumer_thread");...));

**Comment by npwoods** [comment]
That won't work in my case because in my case, the original function might exit scope and the reference to `st` would go away.  Also in my case I wouldn't need the `Cow<'static, str>` because I would know enough to avoid using the `ThreadCell` on anything other than the original thread.  In fact, my desire to use `ThreadCell` was created by the fact that simple references are not a viable solution, and I'm forced to move the resource around before using it on the original thread.

I realize that this might not have been clear from my original contrived example.

Thanks!

**Comment by cehteh** [comment]
Closing this as it is not a issue with threadcell
